Add support for py2/py3 RPM builds
C2Devel/python-oath pull request #1
Opened 2020-04-13 11:18 UTC by odivlad

2020-04-14 15:19 UTC, dplyakin requested changes

2020-04-14 15:19 UTC, dplyakin commented on python-oath.spec
> +Release:          CROC0%{?dist}
Коммит надо бы переименовать.

2020-04-14 15:19 UTC, dplyakin commented on python-oath.spec
> +%if %{with python3}
У нас же теперь всегда with python3?

2020-04-14 15:25 UTC, odivlad commented on python-oath.spec
> +Release:          CROC0%{?dist}
Он для тестирования. Перед merge выкину.

2020-04-14 15:25 UTC, odivlad commented on python-oath.spec
> +%if %{with python3}
Тут выше стоит `%bcond_without`. При желании можно будет отключить сборку под py3, запустив `rpmbuild` с ключом `--without python3`. По-умолчанию же py3 собирается.

2020-04-14 16:37 UTC, dplyakin approved these changes

2020-06-03 11:52 UTC, Sharpeye90 commented
@odivlad remove test commit and give me rights to merge this

2020-06-03 11:59 UTC, odivlad commented
Done.

2020-06-03 12:08 UTC, merged